version: "3.9"

networks:
  cloud-net:
    driver: bridge

services:
  # - 1.1 Web Frontend Server 1 (Node 1) -
  web-frontend-server1:
    build: ./web-frontend-server
    container_name: web-frontend-server1
    ports:
      - "18081:80"
    networks:
      - cloud-net
    restart: unless-stopped

  # - 1.2 Web Frontend Server 2 (Node 2) -
  web-frontend-server2:
    build: ./web-frontend-server
    container_name: web-frontend-server2
    ports:
      - "18082:80"
    networks:
      - cloud-net
    restart: unless-stopped

  # - 2. Application Backend Server (Flask API) -
  application-backend-server:
    build: ./application-backend-server
    container_name: application-backend-server
    ports:
      - "8085:8081"
    networks:
      - cloud-net
    restart: unless-stopped
    environment:
      OIDC_ISSUER: "http://authentication-identity-server:8080/realms/realm_52300089"
      OIDC_AUDIENCE: "account"

  # - 3. Relational Database Server (MariaDB) -
  relational-database-server:
    image: mariadb:10
    container_name: relational-database-server
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: minicloud
    ports:
      - "13306:3306"
    volumes:
      - ./relational-database-server/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - cloud-net
    restart: unless-stopped

  # - 4. Authentication Server (Keycloak) -
  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: [ "start-dev" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_URL: "http://localhost:8081"
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - cloud-net

  # - 5. Object Storage Server (MinIO) -
  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: [ "server", "/data", "--console-address", ":9001" ]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped
    networks:
      - cloud-net

  # - 6. Internal DNS Server (Bind9) -
  internal-dns-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: internal-dns-server
    ports:
      - "1053:53/udp"
    volumes:
      - ./internal-dns-server/named.conf:/etc/bind/named.conf:ro
      - ./internal-dns-server/named.conf.options:/etc/bind/named.conf.options:ro
      - ./internal-dns-server/named.conf.local:/etc/bind/named.conf.local:ro
      - ./internal-dns-server/db.cloud.local:/etc/bind/db.cloud.local:ro
    restart: unless-stopped
    networks:
      - cloud-net

  # - 7. Monitoring Node Exporter Server (Prometheus) -
  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    ports:
      - "9100:9100"
    networks:
      - cloud-net

  # - 8. Monitoring Prometheus Server (Prometheus) -
  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - cloud-net

  # - 9. Monitoring Grafana Dashboard Server (Grafana) -
  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    ports:
      - "3000:3000"
    networks:
      - cloud-net

  # - 10. API Gateway Proxy Server (Nginx) -
  api-gateway-proxy-server:
    image: nginx:stable
    container_name: api-gateway-proxy-server
    depends_on:
      - web-frontend-server1
      - web-frontend-server2
      - application-backend-server
      - authentication-identity-server
    ports:
      - "80:80"
    volumes:
      - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cloud-net
    restart: unless-stopped

volumes:
  db-data:
